# Generated by Django 5.2 on 2025-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_remove_produkt_zdjecie_produkt_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
