# Generated by Django 5.2 on 2025-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0003_alter_produkt_obrazek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='cena',
            new_name='cena_netto',
        ),
        migrations.AddField(
            model_name='produkt',
            name='cena_brutto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='ilosc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
