# Generated by Django 5.2 on 2025-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0004_rename_cena_produkt_cena_netto_produkt_cena_brutto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='ilosc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
