# Generated by Django 5.1.6 on 2025-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='zdjecie',
        ),
        migrations.AddField(
            model_name='produkt',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
